name: Retrieval Accuracy

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  eval:
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Rebuild embeddings
        run: npm run ingest

      - name: Ensure embeddings are committed
        run: git diff --exit-code data/embeddings.json

      - name: Run retrieval accuracy suite
        run: npm run eval:accuracy
